# Generated by Django 3.1 on 2021-01-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210104_0637'),
        ('order', '0002_ordertime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderTime',
            new_name='OrderItem',
        ),
    ]
